server {
    listen 80;
    server_name localhost;

    root /srv/tuf;
    autoindex off;

    add_header Cache-Control "no-store" always;

    location /metadata/ {
        try_files $uri =404;
    }

    location /targets/ {
        try_files $uri =404;
    }

    location / {
        return 404;
    }
}
